export const SIGN_UP_REQUEST = "SING_UP_REQUEST";
export const RETRIEVE_USER_REQUEST = "RETRIEVE_USER_REQUEST";

export const SET_CREATION_LOADING = "SET_CREATION_LOADING";
export const SET_CREATION_SUCCESS = "SET_CREATION_SUCCESS";
export const SET_CREATION_ERROR = "SET_CREATION_ERROR";
export const RESET_CREATION_STATE = "CLEAR_CREATION_STATE";
