export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";

export const SET_SESSION_LOADING = "SET_SESSION_LOADING";
export const SET_SESSION_SUCCESS = "SET_SESSION_SUCCESS";
export const SET_SESSION_ERROR = "SET_SESSION_ERROR";
export const RESET_SESSION_STATE = "RESET_SESSION_STATE";
